PATH_EXCEL_DATABASE = "../00-dados-brutos/base_tratada.xlsx"
PATH_SCREENER_PARQUET = "../01-dados-limpos/screener.parquet"
PATH_PORTFOLIO_PARQUET = "../01-dados-limpos/portfolios.parquet"
PATH_PRELAST_PARQUET = "../01-dados-limpos/prelast.parquet"
PATH_VOLUME_PARQUET = "../01-dados-limpos/volume.parquet"
PATH_SHARESOUTSTANDING_PARQUET = "../01-dados-limpos/sharesOutstanding.parquet"

PATH_RESULTADOS = "../02-resultados"
PATH_CALCULATED_PORTFOLIO_DIR = f"{PATH_RESULTADOS}/portfolios/"
PATH_TABELA_RETORNOS = f"{PATH_RESULTADOS}/retornos.parquet"
PATH_TABELA_INDICADORES_PORTFOLIO = f"{PATH_RESULTADOS}/portfolio_results.parquet"
PATH_TABELA_CONCENTRACAO_PORTFOLIO = f"{PATH_RESULTADOS}/portfolio_concentration.parquet"